<a href="https://colab.research.google.com/github/rickygrosvenor-pramanick/learn-ml/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch Fundamentals

Resources: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


## Introduction to Tensors

### Creating Tensors

https://pytorch.org/docs/stable/tensors.html

https://pytorch.org/docs/stable/generated/torch.tensor.html

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [6]:
# reverting from tensor to python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[0]

tensor([7, 8])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [21]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3, 4],
                        [3, 6, 9 ,12],
                        [2, 4, 6, 8]]])
TENSOR

tensor([[[ 1,  2,  3,  4],
         [ 3,  6,  9, 12],
         [ 2,  4,  6,  8]]])

In [22]:
TENSOR.ndim

3

In [23]:
TENSOR.shape

torch.Size([1, 3, 4])

In [24]:
TENSOR[0]

tensor([[ 1,  2,  3,  4],
        [ 3,  6,  9, 12],
        [ 2,  4,  6,  8]])

In [25]:
TENSOR[0][1]

tensor([ 3,  6,  9, 12])

## Random Tensors
We've established tensors represent some form of data.

And machine learning models such as neural networks manipulate and seek patterns within tensors.

But when building machine learning models with PyTorch, it's rare you'll create tensors by hand (like what we've being doing).

Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...

As a data scientist, you can define how the machine learning model starts (initialization), looks at data (representation) and updates (optimization) its random numbers.

We'll get hands on with these steps later on.

For now, let's see how to create a tensor of random numbers.

We can do so using `torch.rand()` and passing in the size parameter.

In [29]:
## Creating Random Tensors with `torch.rand()`
random = torch.rand(size=(1,3,4))
random

tensor([[[0.7179, 0.1499, 0.9499, 0.4348],
         [0.1632, 0.2235, 0.1933, 0.5620],
         [0.9770, 0.3595, 0.6568, 0.5090]]])

In [30]:
random.shape

torch.Size([1, 3, 4])

In [31]:
## Creating a Random Tensor which is similar to an image tensor
random_image = torch.rand(size=(224, 244, 3)) # height, width, colour channels (R, G, B)
random_image.shape

torch.Size([224, 244, 3])

In [32]:
random_image.ndim

3