<a href="https://colab.research.google.com/github/rickygrosvenor-pramanick/learn-ml/blob/main/pytorch/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch Fundamentals

Resources: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


## Introduction to Tensors

### Creating Tensors

https://pytorch.org/docs/stable/tensors.html

https://pytorch.org/docs/stable/generated/torch.tensor.html

In [4]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# reverting from tensor to python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3, 4],
                        [3, 6, 9 ,12],
                        [2, 4, 6, 8]]])
TENSOR

tensor([[[ 1,  2,  3,  4],
         [ 3,  6,  9, 12],
         [ 2,  4,  6,  8]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 4])

In [17]:
TENSOR[0]

tensor([[ 1,  2,  3,  4],
        [ 3,  6,  9, 12],
        [ 2,  4,  6,  8]])

In [18]:
TENSOR[0][1]

tensor([ 3,  6,  9, 12])

## Random Tensors
We've established tensors represent some form of data.

And machine learning models such as neural networks manipulate and seek patterns within tensors.

But when building machine learning models with PyTorch, it's rare you'll create tensors by hand (like what we've being doing).

Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...

As a data scientist, you can define how the machine learning model starts (initialization), looks at data (representation) and updates (optimization) its random numbers.

We'll get hands on with these steps later on.

For now, let's see how to create a tensor of random numbers.

We can do so using `torch.rand()` and passing in the size parameter.

In [19]:
## Creating Random Tensors with `torch.rand()`
random = torch.rand(size=(1,3,4))
random

tensor([[[0.6266, 0.4704, 0.8995, 0.6434],
         [0.5301, 0.6404, 0.8839, 0.3470],
         [0.5116, 0.2726, 0.9331, 0.8943]]])

In [20]:
random.shape

torch.Size([1, 3, 4])

In [21]:
## Creating a Random Tensor which is similar to an image tensor
random_image = torch.rand(size=(224, 244, 3)) # height, width, colour channels (R, G, B)
random_image.shape

torch.Size([224, 244, 3])

In [22]:
random_image.ndim

3

## Zeros and ones

Sometimes you'll just want to fill tensors with zeros or ones.

This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know not to learn them).

Let's create a tensor full of zeros with `torch.zeros()`

Again, the `size` parameter comes into play.

In [24]:
# Create a tensor of zeros
zero_tensor = torch.zeros(size=(3,4,2))
zero_tensor

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]])

In [28]:
# Create a tensor of ones
ones_tensor = torch.ones(size=(3,4), dtype=int)
ones_tensor

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

## Creating a range and tensors like

Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use `torch.arange(start, end, step)` to do so.

Where:

    start = start of range (e.g. 0)
    end = end of range (e.g. 10)
    step = how many steps in between each value (e.g. 1)


In [29]:
# Use torch.arange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

<ipython-input-29-a09072c806d9>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])



Sometimes you might want one tensor of a certain type with the same shape as another tensor.

For example, a tensor of all zeros with the same shape as a previous tensor.

To do so you can use `torch.zeros_like(input)` or `torch.ones_like(input)` which return a tensor filled with zeros or ones in the same shape as the input respectively.


In [ ]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros