<a href="https://colab.research.google.com/github/rickygrosvenor-pramanick/learn-ml/blob/main/pytorch/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch Fundamentals

Resources: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1+cu121


## Introduction to Tensors

### Creating Tensors

https://pytorch.org/docs/stable/tensors.html

https://pytorch.org/docs/stable/generated/torch.tensor.html

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# reverting from tensor to python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3, 4],
                        [3, 6, 9 ,12],
                        [2, 4, 6, 8]]])
TENSOR

tensor([[[ 1,  2,  3,  4],
         [ 3,  6,  9, 12],
         [ 2,  4,  6,  8]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 4])

In [16]:
TENSOR[0]

tensor([[ 1,  2,  3,  4],
        [ 3,  6,  9, 12],
        [ 2,  4,  6,  8]])

In [17]:
TENSOR[0][1]

tensor([ 3,  6,  9, 12])

## Random Tensors
We've established tensors represent some form of data.

And machine learning models such as neural networks manipulate and seek patterns within tensors.

But when building machine learning models with PyTorch, it's rare you'll create tensors by hand (like what we've being doing).

Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...

As a data scientist, you can define how the machine learning model starts (initialization), looks at data (representation) and updates (optimization) its random numbers.

We'll get hands on with these steps later on.

For now, let's see how to create a tensor of random numbers.

We can do so using `torch.rand()` and passing in the size parameter.

In [18]:
## Creating Random Tensors with `torch.rand()`
random = torch.rand(size=(1,3,4))
random

tensor([[[0.8933, 0.2729, 0.0642, 0.3227],
         [0.3262, 0.3538, 0.9795, 0.1432],
         [0.5414, 0.3120, 0.0877, 0.6006]]])

In [19]:
random.shape

torch.Size([1, 3, 4])

In [20]:
## Creating a Random Tensor which is similar to an image tensor
random_image = torch.rand(size=(224, 244, 3)) # height, width, colour channels (R, G, B)
random_image.shape

torch.Size([224, 244, 3])

In [21]:
random_image.ndim

3

## Zeros and ones

Sometimes you'll just want to fill tensors with zeros or ones.

This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know not to learn them).

Let's create a tensor full of zeros with `torch.zeros()`

Again, the `size` parameter comes into play.

In [22]:
# Create a tensor of zeros
zero_tensor = torch.zeros(size=(3,4,2))
zero_tensor

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]])

In [23]:
# Create a tensor of ones
ones_tensor = torch.ones(size=(3,4), dtype=int)
ones_tensor

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

## Creating a range and tensors like

Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use `torch.arange(start, end, step)` to do so.

Where:

    start = start of range (e.g. 0)
    end = end of range (e.g. 10)
    step = how many steps in between each value (e.g. 1)


In [24]:
# Use torch.arange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

<ipython-input-24-a404776195c1>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])



Sometimes you might want one tensor of a certain type with the same shape as another tensor.

For example, a tensor of all zeros with the same shape as a previous tensor.

To do so you can use `torch.zeros_like(input)` or `torch.ones_like(input)` which return a tensor filled with zeros or ones in the same shape as the input respectively.


In [25]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes
**Note:** Tensor Datatypes is one of the 3 big errors to run into in PyTorch and Deep Learning:

1. Tensors not having the right datatypes for operations - compatibility
2. Tensors not having the right shape for operations
3. Tensors not on the right devices for operations (i.e. one on cpu and one on gpu)


In [29]:
# Float 32 Tensor - Default Datatypes (Single Precision)
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default cpu
                               requires_grad=False) # if True, operations performed on the tensor are recorded
float_32_tensor

tensor([3., 6., 9.])

In [30]:
float_32_tensor.dtype

torch.float32

In [37]:
float_16_tensor = float_32_tensor.type(torch.float16)

float_16_tensor.dtype

torch.float16

Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:

    shape - what shape is the tensor? (some operations require specific shape rules)
    dtype - what datatype are the elements within the tensor stored in?
    device - what device is the tensor stored on? (usually GPU or CPU)

Remember to use the following:
1. `tensor.shape`
2. `tensor.dtype`
3. `tensor.device`

Let's create a random tensor and find out details about it.

In [41]:
# Create a Tensor
some_tensor = torch.rand(size=(3, 4))

# Find out details about it
print(some_tensor)
print(f"Datatype is: {some_tensor.dtype}")
print(f"Shape is: {some_tensor.shape}")
print(f"Device is: {some_tensor.device}")

tensor([[0.4927, 0.8932, 0.8693, 0.0940],
        [0.3254, 0.1901, 0.2002, 0.6876],
        [0.7757, 0.1660, 0.4905, 0.3795]])
Datatype is: torch.float32
Shape is: torch.Size([3, 4])
Device is: cpu


## Manipulating Tensors

In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between:

    Addition
    Substraction
    Multiplication (element-wise)
    Division
    Matrix multiplication

And that's it. Sure there are a few more here and there but these are the basic building blocks of neural networks.

Stacking these building blocks in the right way, you can create the most sophisticated of neural networks (just like lego!).

### Basic Operations

Let's start with a few of the fundamental operations, addition (+), subtraction (-), mutliplication (*).

They work just as you think they would.

In [53]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10


tensor([11, 12, 13])

In [54]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

Notice how the tensor values above didn't end up being `tensor([110, 120, 130])`, this is because the values inside the tensor don't change unless they're reassigned.

In [55]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [56]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

PyTorch also has a bunch of built-in functions like `torch.mul()` (short for multiplication) and `torch.add()` to perform basic operations.

In [57]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [58]:
# Original tensor is still unchanged
tensor

tensor([1, 2, 3])

In [59]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
