In [2]:
import numpy as np

## Datatypes & Attributes

In [3]:
# Numpy's main datatype is a ndarray - n dimensional array
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1, 2.0, 3.3], [4, 5, 6.5]])

a3 = np.array([[[x for x in range(1, 4)],
               [x for x in range(4, 7)],
               [x for x in range (7, 10)]],
               [[x for x in range (10, 13)],
                [x for x in range (13, 16)],
                [x for x in range (16, 19)]]])

In [7]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
(a1.ndim, a2.ndim, a3.ndim)

(1, 2, 3)

In [13]:
(a1.dtype, a2.dtype, a3.dtype)

(dtype('int64'), dtype('float64'), dtype('int64'))

In [14]:
(a1.size, a2.size, a3.size)

(3, 6, 18)

In [15]:
(type(a1), type(a2), type(a3))

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## 2. Creating Arrays

In [16]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [18]:
ones = np.ones((2, 3, 3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [20]:
zeros = np.zeros((3, 2, 3), dtype=int)
zeros

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [21]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [23]:
random_array = np.random.randint(low=4, high=17, size=(3, 2, 4))
random_array

array([[[ 8,  9, 10,  4],
        [ 6,  7, 15,  9]],

       [[ 4, 13,  5,  9],
        [11, 15,  6, 10]],

       [[10,  4, 14,  5],
        [ 5, 14,  4,  9]]])

In [24]:
random_array.size

24

In [28]:
random_array_2 = np.random.random(size=(3, 2, 4))
random_array_2

array([[[0.95574569, 0.63478148, 0.41925012, 0.36438244],
        [0.67461144, 0.00963563, 0.23607259, 0.44840239]],

       [[0.87990964, 0.8909569 , 0.78664684, 0.1251247 ],
        [0.145218  , 0.59580387, 0.86927526, 0.17155028]],

       [[0.51956525, 0.40640494, 0.8111319 , 0.93648555],
        [0.71476567, 0.0316983 , 0.11854063, 0.59121593]]])

In [32]:
random_array_3 = np.random.rand(3, 2, 4)
random_array_3

array([[[0.813378  , 0.11946188, 0.83575442, 0.97812053],
        [0.23211784, 0.26877562, 0.39770778, 0.90535586]],

       [[0.06387306, 0.45119255, 0.4155699 , 0.24427336],
        [0.99931006, 0.75040665, 0.78687022, 0.46036592]],

       [[0.58301515, 0.57737343, 0.59569376, 0.54053128],
        [0.20800749, 0.3964929 , 0.24332759, 0.44117021]]])

In [38]:
# Pseudo-random numbers - helps produce random numbers which are reproduceable
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## 3. Viewing Arrays and Matrices

In [40]:
# Finds all the unique items in an array
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a1[0]

1

In [42]:
a2[0]

array([1. , 2. , 3.3])

In [43]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [53]:
np.random.seed(seed=1009320940)
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[5, 8, 6, 0, 5],
         [6, 2, 0, 2, 6],
         [6, 0, 9, 0, 0],
         [3, 5, 0, 2, 7]],

        [[5, 1, 9, 3, 4],
         [7, 7, 1, 7, 4],
         [7, 5, 3, 9, 2],
         [4, 2, 0, 9, 3]],

        [[7, 6, 3, 9, 2],
         [5, 1, 6, 9, 2],
         [4, 0, 7, 0, 7],
         [7, 0, 0, 0, 2]]],


       [[[5, 6, 1, 0, 3],
         [1, 1, 9, 1, 8],
         [9, 5, 1, 9, 8],
         [6, 5, 4, 7, 7]],

        [[4, 6, 8, 1, 6],
         [4, 6, 0, 6, 9],
         [8, 5, 9, 6, 5],
         [8, 5, 9, 1, 2]],

        [[1, 2, 8, 1, 2],
         [5, 1, 1, 1, 4],
         [5, 7, 4, 0, 0],
         [7, 1, 1, 2, 7]]]])

In [54]:
a4[:1, :2, :3, :4]

array([[[[5, 8, 6, 0],
         [6, 2, 0, 2],
         [6, 0, 9, 0]],

        [[5, 1, 9, 3],
         [7, 7, 1, 7],
         [7, 5, 3, 9]]]])

In [55]:
# Lets say we want the first 4 numbers from the array [8, 5, 9, 6, 5]
a4[1, 1, 2, :4]

array([8, 5, 9, 6])

In [57]:
# Lets say we want the last 3 numbers from the array [5, 7, 4, 0, 0]
a4[1, 2, 2, 2:]

array([4, 0, 0])

## 4. Manipulating and Comparing Arrays and Matrices

### Arithmetics

In [58]:
a1

array([1, 2, 3])

In [61]:
ones = np.ones(3, dtype=int)
ones

array([1, 1, 1])

In [84]:
# Add elements in the same position in both arrays
a1 + ones
np.add(a1, ones)

array([2, 3, 4])

In [85]:
a1 - ones
np.subtract(a1, ones)

array([0, 1, 2])

In [87]:
a1 * ones

array([1, 2, 3])

In [66]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [69]:
# Smaller array is broadcast across larger array as they have compatible shapes i.e 
# innermost arrays both have length 3
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [71]:
# On the other hand, this broadcasting would be incompatible
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [72]:
# So to make this compatible, we need to reshape a2 such that it is compatible with a3 (or vice versa)

In [73]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [74]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [75]:
# One approach may be to make a3's shape (3, 2, 3) instead of (2, 3, 3)
a3_reshaped = np.reshape(a3, newshape=(3,2,3))
a3_reshaped

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [77]:
a2 * a3_reshaped

array([[[  1. ,   4. ,   9.9],
        [ 16. ,  25. ,  39. ]],

       [[  7. ,  16. ,  29.7],
        [ 40. ,  55. ,  78. ]],

       [[ 13. ,  28. ,  49.5],
        [ 64. ,  85. , 117. ]]])

In [78]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [79]:
a1 / ones

array([1., 2., 3.])

In [80]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [82]:
# Floor Division
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [88]:
a2 ** 2
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [90]:
a1 % 2
np.mod(a1, 2)

array([1, 0, 1])

In [91]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [92]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])