In [1]:
import numpy as np

## Datatypes & Attributes

In [2]:
# Numpy's main datatype is a ndarray - n dimensional array
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3], [4, 5, 6.5]])

a3 = np.array([[[x for x in range(1, 4)],
               [x for x in range(4, 7)],
               [x for x in range (7, 10)]],
               [[x for x in range (10, 13)],
                [x for x in range (13, 16)],
                [x for x in range (16, 19)]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
(a1.ndim, a2.ndim, a3.ndim)

(1, 2, 3)

In [11]:
(a1.dtype, a2.dtype, a3.dtype)

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
(a1.size, a2.size, a3.size)

(3, 6, 18)

In [13]:
(type(a1), type(a2), type(a3))

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

## 2. Creating Arrays

In [14]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [15]:
ones = np.ones((2, 3, 3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [16]:
zeros = np.zeros((3, 2, 3), dtype=int)
zeros

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [17]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [18]:
random_array = np.random.randint(low=4, high=17, size=(3, 2, 4))
random_array

array([[[13,  6, 11, 12],
        [14, 11, 11, 12]],

       [[ 6, 11, 13,  8],
        [15, 15,  6, 16]],

       [[ 5, 13, 10,  9],
        [13, 11, 10, 15]]])

In [19]:
random_array.size

24

In [20]:
random_array_2 = np.random.random(size=(3, 2, 4))
random_array_2

array([[[0.27800892, 0.82017655, 0.92995859, 0.89720208],
        [0.98743167, 0.61338767, 0.34810566, 0.98425325]],

       [[0.6275053 , 0.1964891 , 0.78378882, 0.17609989],
        [0.22730009, 0.3099875 , 0.22162557, 0.82936587]],

       [[0.54894568, 0.91163301, 0.18886691, 0.97085683],
        [0.29683441, 0.57310766, 0.58144039, 0.09992012]]])

In [21]:
random_array_3 = np.random.rand(3, 2, 4)
random_array_3

array([[[0.11636519, 0.1672458 , 0.8445171 , 0.57947472],
        [0.80520522, 0.54037224, 0.58119389, 0.6426369 ]],

       [[0.34922947, 0.34031012, 0.59570439, 0.37312034],
        [0.69193263, 0.6383937 , 0.46357865, 0.18475853]],

       [[0.96652653, 0.75857173, 0.88465882, 0.40018763],
        [0.90026833, 0.6846948 , 0.85768492, 0.04764893]]])

In [22]:
# Pseudo-random numbers - helps produce random numbers which are reproduceable
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## 3. Viewing Arrays and Matrices

In [23]:
# Finds all the unique items in an array
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
a1[0]

1

In [25]:
a2[0]

array([1. , 2. , 3.3])

In [26]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [28]:
np.random.seed(seed=1009320940)
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[5, 8, 6, 0, 5],
         [6, 2, 0, 2, 6],
         [6, 0, 9, 0, 0],
         [3, 5, 0, 2, 7]],

        [[5, 1, 9, 3, 4],
         [7, 7, 1, 7, 4],
         [7, 5, 3, 9, 2],
         [4, 2, 0, 9, 3]],

        [[7, 6, 3, 9, 2],
         [5, 1, 6, 9, 2],
         [4, 0, 7, 0, 7],
         [7, 0, 0, 0, 2]]],


       [[[5, 6, 1, 0, 3],
         [1, 1, 9, 1, 8],
         [9, 5, 1, 9, 8],
         [6, 5, 4, 7, 7]],

        [[4, 6, 8, 1, 6],
         [4, 6, 0, 6, 9],
         [8, 5, 9, 6, 5],
         [8, 5, 9, 1, 2]],

        [[1, 2, 8, 1, 2],
         [5, 1, 1, 1, 4],
         [5, 7, 4, 0, 0],
         [7, 1, 1, 2, 7]]]])

In [29]:
a4[:1, :2, :3, :4]

array([[[[5, 8, 6, 0],
         [6, 2, 0, 2],
         [6, 0, 9, 0]],

        [[5, 1, 9, 3],
         [7, 7, 1, 7],
         [7, 5, 3, 9]]]])

In [30]:
# Lets say we want the first 4 numbers from the array [8, 5, 9, 6, 5]
a4[1, 1, 2, :4]

array([8, 5, 9, 6])

In [31]:
# Lets say we want the last 3 numbers from the array [5, 7, 4, 0, 0]
a4[1, 2, 2, 2:]

array([4, 0, 0])

## 4. Manipulating and Comparing Arrays and Matrices

### Arithmetics

In [32]:
a1

array([1, 2, 3])

In [33]:
ones = np.ones(3, dtype=int)
ones

array([1, 1, 1])

In [34]:
# Add elements in the same position in both arrays
a1 + ones
np.add(a1, ones)

array([2, 3, 4])

In [35]:
a1 - ones
np.subtract(a1, ones)

array([0, 1, 2])

In [36]:
a1 * ones

array([1, 2, 3])

In [37]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [38]:
# Smaller array is broadcast across larger array as they have compatible shapes i.e 
# innermost arrays both have length 3
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [39]:
# On the other hand, this broadcasting would be incompatible
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
# So to make this compatible, we need to reshape a2 such that it is compatible with a3 (or vice versa)

In [ ]:
a2

In [ ]:
a3

In [ ]:
# One approach may be to make a3's shape (3, 2, 3) instead of (2, 3, 3)
a3_reshaped = np.reshape(a3, newshape=(3,2,3))
a3_reshaped

In [ ]:
a2 * a3_reshaped

In [ ]:
a2

In [ ]:
a1 / ones

In [ ]:
a2 / a1

In [ ]:
# Floor Division
a2 // a1

In [ ]:
a2 ** 2
np.square(a2)

In [ ]:
a1 % 2
np.mod(a1, 2)

In [ ]:
np.exp(a1)

In [ ]:
np.log(a1)

### Aggregation
Performing the same operation on a number of objects

In [41]:
listy = [1, 2, 3]
type(listy)

list

In [42]:
sum(listy)

6

In [43]:
a1

array([1, 2, 3])

In [44]:
type(a1)

numpy.ndarray

In [45]:
np.sum(a1)

6

In [47]:
a1.dtype

dtype('int64')

In [48]:
massive_array = np.random.random(1000000)
massive_array.size

1000000

In [49]:
massive_array[:1000]

array([1.05860828e-01, 8.51854238e-01, 3.39370038e-01, 3.76515699e-01,
       1.00324557e-02, 1.39641128e-01, 5.94414977e-01, 5.76641935e-01,
       7.52479942e-01, 9.50845230e-01, 5.47160773e-01, 7.28684763e-01,
       3.30800005e-01, 8.72102365e-01, 4.07999827e-01, 2.02567088e-01,
       6.06218428e-01, 1.52024186e-01, 8.45044782e-01, 9.62051641e-01,
       3.29131721e-01, 4.47891019e-01, 6.80232257e-01, 3.78465082e-01,
       1.40878807e-01, 4.80854210e-01, 8.75557590e-01, 4.36608683e-01,
       7.71618122e-01, 9.37113565e-01, 7.29862904e-01, 4.20369831e-01,
       7.14834795e-01, 8.99701635e-01, 8.22910474e-01, 1.10052036e-01,
       1.59258574e-01, 7.81322683e-02, 2.36606878e-01, 6.60435829e-01,
       9.00054277e-01, 3.05779556e-01, 3.91376209e-01, 5.13216045e-01,
       8.76682054e-01, 1.60566438e-01, 4.62787041e-01, 4.36411414e-01,
       5.94807018e-01, 4.45198429e-01, 7.13104046e-02, 7.42716254e-01,
       7.99252526e-01, 1.26289387e-01, 9.56505176e-01, 6.05127004e-02,
      

In [51]:
%timeit sum(massive_array) #In built Python Sum
%timeit np.sum(massive_array) #NumPy's Sum

73.4 ms ± 501 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
302 µs ± 1.14 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [52]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [54]:
np.mean(a2)

3.6333333333333333

In [55]:
np.max(a2)

6.5

In [56]:
np.min(a2)

1.0

In [59]:
# The Standard Deviation is a measure of how spread out numbers are.
np.std(a2)

1.8226964152656422

In [60]:
# The average of the squared differences from the Mean.
# High Variance = Data is More Spread Out
np.var(a2)

3.3222222222222224